export enum StatusMsg {
  ACCESS_DENIED = 'Access Denied',
  BAD_REQUEST = 'Bad Request',
  DATA_NOT_FOUND = 'Data Not Found',
  DUPLICATE_ENTRY = 'Duplicate Entry',
  FORBIDDEN = 'Forbidden',
  INVALID_INPUT = 'Invalid Input',
  LOGIN_REQUIRED = 'Login Required',
  LOGOUT_SUCCESS = 'Logout Successful',
  NOT_FOUND = 'Not Found',
  PAGE_NOT_FOUND = 'Page Not Found',
  SERVER_ERROR = 'Server Error',
  SUCCESS = 'Success',
  UNAUTHORIZED = 'Unauthorized'
}

export const divisions = [
  'AML Division',
  'Agent Banking Division',
  'Banking Operation Division',
  'Board Division',
  'Business Development Division',
  'Card Division',
  "Chairman's Secretariat",
  "MD'S Secretariat",
  "DMD'S Secretariat",
  'Credit Administrator Division',
  'Credit Division',
  'Corporate Banking Division',
  'Financial Administrator Division',
  'General Services Division',
  'HR Attachment',
  'Human Resources Division',
  'ICC Division',
  'ICT Division',
  'International Division',
  'Islamic Banking Division',
  'Legal Affairs & Recovery Division',
  'MIS & CIB Division',
  'Public Relation Division',
  'Risk Management Division',
  'SBAC Bank Investment',
  'SENIOR Management',
  'Training Institute',
  'Tresury Division',
  'Trade Processing Unit',
  'Others'
]
